import type { Article, Author, Tag } from "@/lib/types";

type BuildPixel11LaunchArticleArgs = {
  authors: Author[];
  topics: Tag[];
  brands: Tag[];
};

function bySlug<T extends { slug: string }>(items: T[], slug: string) {
  const item = items.find((entry) => entry.slug === slug);
  if (!item) throw new Error(`Missing content term: ${slug}`);
  return item;
}

export function buildPixel11LaunchArticle({ authors, topics, brands }: BuildPixel11LaunchArticleArgs): Article {
  const timHumphreys = bySlug(authors, "tim-humphreys");
  const tags = [
    bySlug(brands, "google"),
    bySlug(topics, "google-pixel-11"),
    bySlug(topics, "smartphones"),
    bySlug(topics, "android"),
    bySlug(topics, "ai"),
    bySlug(topics, "hilight"),
    bySlug(topics, "made-by-google"),
    bySlug(topics, "charging"),
    bySlug(topics, "smartphone-prices"),
    bySlug(topics, "chipsets"),
    bySlug(topics, "system-updates")
  ];

  return {
    id: "pixel-11-launch-2026",
    slug: "google-pixel-11-series-tensor-g6-hilight-price-2026",
    format: "news",
    contentFormat: "analysis",
    title: "Google Pixel 11 Series Arrives with Tensor G6, HiLight, Better Cameras and Higher Starting Prices",
    seo: {
      title: "Google Pixel 11 Series: Specs, HiLight, Prices and Release Date",
      description: "Google has launched the Pixel 11, Pixel 11 Pro, Pixel 11 Pro XL and Pixel 11 Pro Fold with Tensor G6, HiLight, new cameras, Android 17 and higher starting prices."
    },
    subhead: "Google's four-phone Pixel 11 family combines Tensor G6, brighter displays, upgraded cameras, Proactive Assistance, Qi2.2 charging and Pro-only HiLight notifications, while pushing every entry price higher.",
    excerpt: "Google's Pixel 11 family is official, bringing Tensor G6, brighter displays, new camera hardware, Proactive Assistance, Qi2.2 charging and the return of notification lights through HiLight.",
    whyItMatters: "The Google Pixel 11 series is no longer priced as a cheaper flagship alternative. Buyers now need to weigh the storage changes, seven-year support, Pro-only features and unconfirmed silicon details against prices from $899 to $1,899.",
    body: [
      "Google officially launched the Pixel 11 family at Made by Google 2026 in New York on August 12, giving its flagship smartphone line a familiar look, a more ambitious AI layer and one of the most interesting notification systems seen on a mainstream Android phone in years.",
      "The lineup consists of the Pixel 11, Pixel 11 Pro, Pixel 11 Pro XL and Pixel 11 Pro Fold. All four use Google's Tensor G6 platform and Android 17, while the Pro models gain HiLight, a set of coloured LEDs integrated around the rear camera flash that can communicate information while the phone is lying face-down.",
      "The standard Pixel 11 starts at $899, the Pixel 11 Pro at $1,099, the Pixel 11 Pro XL at $1,299 and the Pixel 11 Pro Fold at $1,899. Pre-orders opened August 12, with general retail availability beginning August 20.",
      "Those starting prices are $100 above the cheapest launch configurations of their predecessors. There is an important qualification, however. Google removed 128GB storage from the Pixel 11 and Pixel 11 Pro, so both now begin at 256GB. Their price comparison is less straightforward than a simple $100 increase suggests.",
      "This generation is not about one dramatic redesign. Google is tightening several parts of the Pixel experience at once: camera sensors, display brightness, charging, on-device AI, security and a smartphone assistant that increasingly tries to understand what the user is doing before being explicitly asked.",
      "That may make the Pixel 11 series Google's clearest attempt yet to stop being the cheaper alternative to an iPhone or Galaxy flagship and simply compete as a premium smartphone family in its own right.",
      "## Pixel 11 series: what Google announced",
      "The Pixel 11 family keeps the four-model structure Google established in recent generations.",
      "The standard Pixel 11 is the entry point. It uses a 6.3-inch 120Hz OLED display, 12GB of RAM and 256GB of storage as standard. Unlike older base Pixels, it retains a triple-camera system with a dedicated 5x telephoto lens.",
      "The Pixel 11 Pro uses a 6.3-inch LTPO OLED panel that can vary from 1Hz to 120Hz, while the Pixel 11 Pro XL stretches the same Pro formula to 6.8 inches. Both are offered with 12GB RAM on the 256GB model and 16GB on higher storage configurations.",
      "The Pixel 11 Pro Fold keeps the two-screen foldable format, with a 6.4-inch outer display and an 8-inch inner display. It comes with 16GB of RAM and adds a new gearless hinge and greater claimed structural durability.",
      "Across the range, Google promises seven years of operating-system updates, security updates and Pixel Drops. That commitment matters as flagship prices rise and upgrade cycles become longer. A premium phone increasingly has to justify itself across four, five or seven years rather than a two-year contract.",
      "## Pixel 11 specifications at a glance",
      "[[table:pixel-11-specifications]]",
      "The Pixel 11 Pro Fold battery cell capacity appeared in pre-launch reporting, but Google's launch materials emphasise rated endurance and charging performance rather than a headline capacity figure. tecMAMBO is therefore not treating an unverified pre-launch mAh figure as an official specification.",
      "[[media:pixel-11-product-gallery]]",
      "## Tensor G6 is official, but Google is selective about the silicon details",
      "Tensor G6 is the centre of the Pixel 11 story. Google calls it its fastest and most powerful Pixel chip yet. The company says the CPU delivers 25 percent faster web browsing and 15 percent quicker app launches compared with Tensor G5. Its new Tensor Processing Unit offers 50 percent more compute.",
      "Tensor has rarely been positioned as a benchmark-first alternative to Apple's A-series or Qualcomm's Snapdragon flagships. Google's argument is that custom silicon is valuable because it can optimise the camera, AI, speech and security experiences around which Pixel is built.",
      "There is one area where launch coverage requires caution. Pre-launch and launch-period reporting points to TSMC's 2nm process, but Google has not publicly made the node part of its launch specification.",
      "Earlier reporting identifies a MediaTek M90-series modem, while Google has only publicly confirmed new modem hardware. tecMAMBO therefore treats the TSMC 2nm and MediaTek M90 details as well-supported reporting rather than official Google-confirmed specifications.",
      "That distinction matters on launch day, when months of leaks can suddenly be repeated online as though every detail appeared on stage.",
      "[[media:pixel-11-tensor-g6]]",
      "## What Tensor G6 changes for the user",
      "Google says Tensor G6 improves on-device Gemini processing, camera image processing, app launches, browser responsiveness, energy efficiency, Live Translate, Pro Zoom, Instant Night Sight and device security.",
      "The Pixel 11 Pro and Pro XL also include vapour-chamber cooling designed to sustain performance during demanding workloads. That is relevant because Tensor-powered Pixels have historically attracted criticism for heat, modem efficiency and sustained performance.",
      "A new chip does not erase that history by announcement. Independent battery, thermal, cellular and gaming tests will matter after reviewers have lived with retail devices.",
      "## The standard Pixel 11 gets the genuinely thinner camera bar",
      "Google has not abandoned the horizontal camera bar that became the Pixel's strongest visual identifier. It has cleaned it up.",
      "On the standard Pixel 11, Google says the camera bar is 40 percent thinner than previous base Pixel designs. With a Made by Google case fitted, the company says the phone becomes effectively flat enough to avoid wobbling on a table.",
      "That 40 percent reduction does not apply to the whole range. The Pixel 11 Pro and Pro XL retain a more substantial camera housing because they accommodate larger camera hardware and HiLight.",
      "All three conventional Pixel 11 phones now use edge-to-edge glass across the camera area. The base Pixel 11 comes in Frost, Hibiscus, Pistachio and Obsidian. The Pro and Pro XL come in Canyon, Fog, Olive and matte Obsidian.",
      "[[media:pixel-11-camera-bar-comparison]]",
      "## HiLight brings back the notification LED as part of the camera",
      "HiLight is Google's new coloured LED notification system, built around the camera flash on the Pixel 11 Pro, Pixel 11 Pro XL and Pixel 11 Pro Fold. The normal Pixel 11 does not have HiLight.",
      "When a Pro phone is face-down, HiLight can glow in different colours and patterns to communicate information without requiring the user to turn on the display.",
      "For incoming calls, users can assign custom colours to favourite contacts. For Gemini, HiLight changes its pattern depending on whether Gemini is listening, thinking or responding. Google says message notifications from favourite contacts are planned for a later update.",
      "[[media:pixel-11-hilight]]",
      "This is the old notification LED rebuilt for an era in which phones have become visually quieter on the front and dramatically more complicated on the back. It is also more restrained than Nothing's Glyph approach because Google keeps the lighting close to the camera flash.",
      "Whether HiLight becomes useful will depend on how far Google opens it. A notification light becomes powerful when users can choose exactly which applications and events deserve attention. If the feature remains limited to a few Google-approved scenarios, it risks becoming a beautiful demo that owners forget exists.",
      "For the pre-launch context and the controls this feature still needs, read [our earlier Pixel 11 HiLight analysis](/opinion/pixel-11-glow-hilight-notification-led-leaks).",
      "## The camera story matters more than 120x sounds",
      "The standard Pixel 11 receives a larger 48MP main sensor that Google says has 56 percent greater light sensitivity than the Pixel 10. It keeps a 13MP ultrawide and a 10.8MP 5x telephoto lens. Tensor G6 extends Super Zoom to 30x on the base model.",
      "The Pixel 11 Pro and Pro XL use a 50MP main camera, 48MP ultrawide and upgraded 48MP 5x telephoto. Google says the new telephoto sensor has 30 percent better light sensitivity.",
      "The Pro models then push computational zoom to 120x Pro Zoom. That is not 120x optical zoom. The 5x lens provides the optical reach, while everything beyond that depends on sensor data, cropping, image processing and Google's computational photography models.",
      "The more practical changes may matter more. Google says Night Sight can capture up to 4.5 times faster. Pro models can use Portrait Mode at 5x. Camera Looks provides adjustable image profiles, while Magic Capture records a short video sequence and extracts still images from the moment.",
      "Pixel cameras have rarely depended on the largest hardware specification alone. They succeed when the phone removes decisions and still produces a usable image.",
      "[[media:pixel-11-pro-camera-zoom]]",
      "## Android 17 arrives with Gemini Intelligence and Proactive Assistance",
      "All four Pixel 11 phones ship with Android 17. The more consequential software change is Google's growing Gemini Intelligence layer.",
      "One component is Proactive Assistance. Google has now made proactive assistance part of the Pixel 11 experience, after earlier app teardowns revealed a system designed to use permitted context from the phone to reduce how much a user must explain manually.",
      "The idea is that Gemini can understand that a reservation is approaching, recognise information on screen, help organise a task across applications or surface relevant information without forcing the user to rebuild the entire situation inside a prompt.",
      "The convenience is obvious. So is the privacy question. Users need to know which applications contribute context, what is processed on the device, what reaches Google's servers, how long context is retained and whether individual sources can be disabled.",
      "The best version of proactive AI removes unnecessary taps. The worst creates a phone that watches everything in case it can be helpful. For the privacy and control questions, see [our Pixel 11 Proactive Assistance explainer](/news/pixel-11-proactive-assistance-gemini-context-leak).",
      "## Seven years of updates may be the financially important feature",
      "Every Pixel 11 model receives seven years of operating-system, security and Pixel Drop updates. A Pixel 11 bought in 2026 is intended to remain supported well into the 2030s.",
      "At $899 and above, the Pixel is no longer a cheap flagship alternative. The value case depends on how long the phone remains useful, which makes battery replacement, repair pricing, spare parts, storage, long-term performance and resale value part of the buying decision.",
      "Seven years of software updates are excellent. Seven years with an exhausted battery and unavailable repair parts would be much less impressive. Google's promise must be evaluated alongside its repair ecosystem.",
      "## Qi2.2 and Pixelsnap make magnetic charging normal on Pixel",
      "All four phones support Qi2.2 wireless charging up to 25W through Google's Pixelsnap ecosystem. The practical benefit is not simply faster wireless charging. Magnets make accessories predictable: chargers align, stands hold the phone correctly and wallets or mounts use a known attachment point.",
      "Apple proved that magnetic positioning can turn wireless charging from a surface into an accessory platform. Google is now making equivalent behaviour part of the Pixel identity.",
      "[[media:pixel-11-pixelsnap]]",
      "## Pixel 11 Pro Fold is thinner, lighter and more durable",
      "The Pixel 11 Pro Fold is nearly 10 percent lighter and about 1mm thinner than its predecessor. Google says its new glass-fibre composite back cover is designed to be difficult to crack, while a new gearless hinge increases protection for the inner display.",
      "The company claims the device is three times more durable than the previous generation based on its internal testing. Both displays reach up to 3,600 nits peak brightness, and the inner display remains an 8-inch panel designed for multitasking.",
      "The Fold also receives HiLight. Google added a sign-to-text accessibility feature developed with the Deaf community. A user can sign American Sign Language toward the camera, with translations appearing as text on the outer display.",
      "The foldable form makes hands-free signing easier because the phone can support itself partially open. This is an example of a foldable solving a problem that cannot be captured by a normal specification table.",
      "[[media:pixel-11-pro-fold]]",
      "## The $100 price increase needs context",
      "The easiest headline is that every Pixel 11 model costs $100 more. That is technically true when comparing the cheapest launch configuration of each generation. It is not the whole story.",
      "The Pixel 10 and Pixel 10 Pro started with 128GB storage. The Pixel 11 and Pixel 11 Pro start at 256GB. Google says the new entry pricing is therefore comparable with the 256GB versions of the previous generation.",
      "The Pixel 11 Pro XL is harder to defend because its entry model already started at 256GB last generation. The same clearer like-for-like increase applies to the Pixel 11 Pro Fold at $1,899.",
      "There is also a RAM wrinkle. The 256GB Pixel 11 Pro and Pro XL begin at 12GB RAM, while higher storage versions move to 16GB. The previous Pro generation offered 16GB more broadly.",
      "Google has discussed severe memory supply pressures affecting hardware prices in 2026. That context explains the decision. It does not make the trade-off invisible. For the background, read [our Pixel memory and pricing analysis](/news/pixel-11-price-increase-memory-crisis) and [our guide to wider smartphone component costs](/wallet-watch/qualcomm-chip-price-hikes-buy-phone-now-or-wait).",
      "## Pixel 11 pricing and availability",
      "- Pixel 11: $899 for 12GB RAM and 256GB storage.",
      "- Pixel 11 Pro: $1,099 for 12GB RAM and 256GB storage.",
      "- Pixel 11 Pro XL: $1,299 for 12GB RAM and 256GB storage.",
      "- Pixel 11 Pro Fold: $1,899 for 16GB RAM and 256GB storage.",
      "Pre-orders opened on August 12, 2026. Google says general retail availability begins August 20, 2026.",
      "The Pixel 11 series is launching in markets including North America, Europe, Australia, Japan and Taiwan. Kenya is not among the markets listed in current launch reporting, so Kenyan buyers are likely to depend on importers and third-party retailers unless Google expands official distribution.",
      "That matters for local warranty, 5G band compatibility, eSIM support, repairs, replacement parts, Pixelsnap accessory availability, trade-ins and insurance. A US price converted directly into Kenyan shillings is not a realistic estimate of final Kenyan retail cost.",
      "[[media:pixel-11-pricing-graphic]]",
      "## Which Pixel 11 should you buy?",
      "### Pixel 11: the sensible choice",
      "The standard Pixel 11 starts with 256GB storage, adds the same Tensor G6 chip and retains a dedicated telephoto camera. For most buyers, it likely provides the strongest balance of size, camera flexibility and long-term support. Its main sacrifices are Pro display technology, the larger Pro camera sensors, 120x Pro Zoom and HiLight.",
      "### Pixel 11 Pro: the compact enthusiast option",
      "The 6.3-inch Pixel 11 Pro is for buyers who want Google's strongest cameras without carrying a very large phone. At $1,099, it competes directly with established premium devices from Apple and Samsung.",
      "### Pixel 11 Pro XL: the complete slab flagship",
      "The Pro XL combines the 6.8-inch display, strongest conventional Pixel camera system and fastest wired charging in the range. At $1,299 before higher storage, it is an obvious luxury purchase.",
      "### Pixel 11 Pro Fold: the productivity experiment",
      "The Fold is for someone with a real use for an 8-inch display in a pocket. At $1,899, the buyer should know what that larger screen will replace: a tablet, a reading device, a work device or part of a laptop workflow.",
      "## Made by Google is becoming an entertainment show",
      "Made by Google 2026 was hosted by Trevor Noah in New York, with athletes, artists and media personalities appearing around the event. That format says something about where Pixel sits today.",
      "Google is no longer presenting Pixel mainly to developers and Android enthusiasts. It wants mainstream cultural relevance and is selling fashion, photography, communication and personal AI rather than a reference Android device.",
      "That is consistent with the pricing. A company asking $1,299 for its conventional flagship is not trying to be the clever alternative anymore. It is asking to be considered alongside the default premium choices.",
      "## What Google still needs to prove",
      "### Has modem reliability improved?",
      "Google says the phones use new modem hardware. The supplier name matters less than whether cellular efficiency and standby drain improve.",
      "### Can Tensor G6 sustain performance?",
      "Vapour-chamber cooling and efficiency claims sound promising. Independent thermal tests will show whether Pro models remain fast during camera use, navigation and gaming.",
      "### Does HiLight become an ecosystem?",
      "The hardware becomes important only if Google expands the number of applications and events that can use it.",
      "### Is 12GB enough for entry Pro models?",
      "Twelve gigabytes is not a small amount, but Google is selling a premium AI phone with seven years of support while reducing baseline RAM from the previous Pro generation.",
      "### Does Proactive Assistance feel helpful rather than intrusive?",
      "A phone that understands context can save time. A phone that constantly surfaces suggestions can become exhausting. Google needs to teach Gemini when silence is the correct response.",
      "## The tecMAMBO take",
      "The Pixel 11 series is Google's most mature flagship lineup yet, and that maturity comes with a different kind of pressure. There is no budget-flagship excuse left.",
      "At $899 for the entry model, $1,299 for the Pro XL and $1,899 for the Fold, Google is charging premium-phone money and must deliver premium-phone consistency.",
      "The encouraging parts are easy to find. The standard Pixel 11 starts at 256GB. The Pro cameras receive useful hardware upgrades. Qi2.2 magnetic charging is normal across the family. HiLight gives the old notification LED an elegant second life. Tensor G6 focuses on efficiency and on-device intelligence. Seven years of updates make the phones easier to justify as long-term purchases.",
      "The concerns are equally clear. Google reduced baseline Pro RAM while increasing its AI ambitions. The Pro XL and Fold carry unambiguous price increases. Modem and thermal claims need real-world proof. Proactive Assistance needs unusually good privacy controls if Google expects users to let Gemini understand more of what happens across their phones.",
      "The Pixel used to be easy to recommend because it offered Google's best software ideas below the obvious flagship competition. Pixel 11 changes the proposition.",
      "Google is saying its phone belongs in the same premium conversation as the iPhone and Galaxy S series. The 2026 Pixel question is no longer whether it is good for a Pixel. It is whether the phone is good enough for the money.",
      "[[media:pixel-11-closing-lifestyle]]"
    ],
    comparisonTables: [
      {
        id: "pixel-11-specifications",
        caption: "Google Pixel 11 series specifications and US starting prices",
        columns: ["Pixel 11", "Pixel 11 Pro", "Pixel 11 Pro XL", "Pixel 11 Pro Fold"],
        rows: [
          { label: "Display", values: ["6.3-inch Actua OLED, 60 to 120Hz", "6.3-inch Super Actua LTPO OLED, 1 to 120Hz", "6.8-inch Super Actua LTPO OLED, 1 to 120Hz", "6.4-inch outer OLED, 8-inch inner OLED"] },
          { label: "Processor", values: ["Tensor G6", "Tensor G6", "Tensor G6", "Tensor G6"] },
          { label: "Security chip", values: ["Titan M3", "Titan M3", "Titan M3", "Titan M3"] },
          { label: "RAM", values: ["12GB", "12GB or 16GB", "12GB or 16GB", "16GB"] },
          { label: "Base storage", values: ["256GB", "256GB", "256GB", "256GB"] },
          { label: "Main camera", values: ["48MP", "50MP", "50MP", "48MP"] },
          { label: "Ultrawide", values: ["13MP", "48MP", "48MP", "10.5MP"] },
          { label: "Telephoto", values: ["10.8MP, 5x optical", "48MP, 5x optical", "48MP, 5x optical", "10.8MP, 5x optical"] },
          { label: "Maximum still-image zoom", values: ["30x Super Zoom", "120x computational Pro Zoom", "120x computational Pro Zoom", "30x Super Zoom"] },
          { label: "Battery", values: ["4,985mAh", "4,850mAh", "5,115mAh", "Google rates it for 24+ hour use"] },
          { label: "Wired charging", values: ["Up to 30W", "Up to 30W", "Up to 45W", "Up to 30W"] },
          { label: "Wireless charging", values: ["Qi2.2, up to 25W", "Qi2.2, up to 25W", "Qi2.2, up to 25W", "Qi2.2, up to 25W"] },
          { label: "HiLight", values: ["No", "Yes", "Yes", "Yes"] },
          { label: "Operating system", values: ["Android 17", "Android 17", "Android 17", "Android 17"] },
          { label: "Update promise", values: ["7 years", "7 years", "7 years", "7 years"] },
          { label: "US starting price", values: ["$899", "$1,099", "$1,299", "$1,899"] }
        ]
      }
    ],
    mediaSlots: [
      {
        id: "pixel-11-product-gallery",
        type: "image",
        status: "placeholder",
        placement: "after-specifications-table",
        caption: "The Pixel 11 lineup spans a compact base phone, two Pro sizes and Google's latest foldable.",
        alt: "Four individual Google Pixel 11 models shown as a product gallery.",
        credit: "Google",
        licensingNote: "Awaiting a licensed four-panel gallery asset.",
        aspectRatio: "16:9",
        width: 1600,
        height: 900
      },
      {
        id: "pixel-11-tensor-g6",
        type: "image",
        status: "ready",
        placement: "after-tensor-g6-section",
        caption: "Tensor G6 increases TPU compute by 50 percent and powers Google's latest on-device Gemini features.",
        alt: "Official Google Tensor G6 processor graphic.",
        credit: "Google",
        licensingNote: "Official image from Google's Pixel 11 launch article.",
        aspectRatio: "16:9",
        src: "/articles/pixel-11-tensor-g6-google.webp",
        width: 1600,
        height: 899
      },
      {
        id: "pixel-11-camera-bar-comparison",
        type: "image",
        status: "placeholder",
        placement: "after-camera-bar-section",
        caption: "Google reduced the standard Pixel 11 camera bar by 40 percent, while Pro models retain a larger camera assembly.",
        alt: "Side profiles comparing the Pixel 11 and Pixel 11 Pro camera housings.",
        credit: "Google",
        licensingNote: "Awaiting a licensed side-profile comparison.",
        aspectRatio: "16:9",
        width: 1600,
        height: 900
      },
      {
        id: "pixel-11-hilight",
        type: "image",
        status: "ready",
        placement: "within-hilight-section",
        caption: "HiLight uses coloured LED patterns for calls, Gemini activity and future notification functions.",
        alt: "Close-up of HiLight glowing around the rear camera flash on a Canyon Pixel 11 Pro.",
        credit: "Google",
        licensingNote: "Still captured from Google's official Pixel 11 launch video.",
        aspectRatio: "16:9",
        src: "/articles/pixel-11-hilight-google.webp",
        width: 1600,
        height: 900
      },
      {
        id: "pixel-11-pro-camera-zoom",
        type: "image",
        status: "placeholder",
        placement: "after-camera-section",
        caption: "The Pro phones use an upgraded 48MP 5x telephoto camera and computational Pro Zoom up to 120x.",
        alt: "Pixel 11 Pro XL camera system with 5x and 120x framing examples.",
        credit: "Google",
        licensingNote: "Awaiting licensed camera samples with reliable zoom labels.",
        aspectRatio: "16:9",
        width: 1600,
        height: 900
      },
      {
        id: "pixel-11-pixelsnap",
        type: "image",
        status: "ready",
        placement: "after-pixelsnap-section",
        caption: "The Pixel 11 family supports up to 25W Qi2.2 wireless charging through Google's Pixelsnap ecosystem.",
        alt: "Canyon Pixel 11 Pro attached magnetically to a Google Pixelsnap Ring Stand on a desk.",
        credit: "Google",
        licensingNote: "Official image from Google's Pixelsnap launch article.",
        aspectRatio: "16:9",
        src: "/articles/pixel-11-pixelsnap-google.webp",
        width: 1440,
        height: 810
      },
      {
        id: "pixel-11-pro-fold",
        type: "image",
        status: "ready",
        placement: "after-fold-section",
        caption: "The Pixel 11 Pro Fold is thinner and lighter, uses a new gearless hinge and adds HiLight.",
        alt: "Obsidian Google Pixel 11 Pro Fold shown open from the front and back.",
        credit: "Google",
        licensingNote: "Official image from Google's Pixel 11 Pro Fold launch article.",
        aspectRatio: "16:9",
        src: "/articles/pixel-11-pro-fold-google.webp",
        width: 1600,
        height: 900
      },
      {
        id: "pixel-11-pricing-graphic",
        type: "infographic",
        status: "placeholder",
        placement: "after-pricing-section",
        caption: "The four entry prices are higher, but storage and RAM changes complicate direct comparisons.",
        alt: "Pixel 11 lineup with US starting prices of $899, $1,099, $1,299 and $1,899.",
        credit: "tecMAMBO",
        licensingNote: "Original pricing graphic has not yet been produced.",
        aspectRatio: "16:9",
        width: 1600,
        height: 900
      },
      {
        id: "pixel-11-closing-lifestyle",
        type: "image",
        status: "placeholder",
        placement: "before-faq",
        caption: "HiLight aims to communicate useful information without requiring more screen time.",
        alt: "Pixel 11 Pro resting face-down on a desk with HiLight active.",
        credit: "Google",
        licensingNote: "Awaiting a suitable licensed lifestyle image.",
        aspectRatio: "16:9",
        width: 1600,
        height: 900
      }
    ],
    author: timHumphreys,
    publishedAt: "2026-08-12T18:35:00+03:00",
    updatedAt: "2026-08-12T18:35:00+03:00",
    readTime: "16 min read",
    image: {
      src: "/articles/google-pixel-11-series-launch-2026.webp",
      alt: "Google Pixel 11 Pro Fold, Pixel 11, Pixel 11 Pro and Pixel 11 Pro XL shown together after the Made by Google 2026 launch.",
      credit: "Google",
      width: 1600,
      height: 900,
      type: "image/webp"
    },
    tags,
    faq: [
      { question: "How much does the Google Pixel 11 cost?", answer: "The Pixel 11 starts at $899 in the United States with 12GB RAM and 256GB storage." },
      { question: "How much are the Pixel 11 Pro and Pixel 11 Pro XL?", answer: "The Pixel 11 Pro starts at $1,099, while the Pixel 11 Pro XL starts at $1,299. Both start with 12GB RAM and 256GB storage." },
      { question: "How much does the Pixel 11 Pro Fold cost?", answer: "The Pixel 11 Pro Fold starts at $1,899 in the United States." },
      { question: "What is Google HiLight?", answer: "HiLight is a coloured LED notification system around the rear camera flash on Pixel 11 Pro, Pixel 11 Pro XL and Pixel 11 Pro Fold. It can indicate selected calls and Gemini activity, with more functions planned." },
      { question: "Does the normal Pixel 11 have HiLight?", answer: "No. HiLight is available on Pixel 11 Pro, Pixel 11 Pro XL and Pixel 11 Pro Fold." },
      { question: "Is Tensor G6 a 2nm TSMC chip?", answer: "Launch-period reporting points to TSMC's 2nm process, but Google has not publicly made the manufacturing node part of its official specification. tecMAMBO treats 2nm as strongly reported rather than Google-confirmed." },
      { question: "Does Pixel 11 use a MediaTek M90 modem?", answer: "Earlier reporting identified a MediaTek M90-series modem. Google confirmed new modem hardware but did not publicly name the supplier in its launch material." },
      { question: "What Android version does Pixel 11 use?", answer: "The Pixel 11 family launches with Android 17." },
      { question: "How long will Google update the Pixel 11?", answer: "Google promises seven years of operating-system, security and Pixel Drop updates." },
      { question: "Does Pixel 11 have magnetic wireless charging?", answer: "Yes. The Pixel 11 family supports Qi2.2 wireless charging up to 25W through Google's Pixelsnap magnetic accessory ecosystem." },
      { question: "When does Pixel 11 go on sale?", answer: "Pre-orders opened August 12, 2026, with general retail availability beginning August 20." },
      { question: "Is Pixel 11 officially available in Kenya?", answer: "Kenya is not listed among the initial launch markets. Buyers should check Google and authorised regional retailers for later expansion." }
    ],
    sources: [
      { label: "Google Blog: The Pixel 11 series: Your most personal Pixel yet", url: "https://blog.google/products-and-platforms/devices/pixel/google-pixel-11-pro-xl/" },
      { label: "Google Blog: Google's most sophisticated foldable: Pixel 11 Pro Fold", url: "https://blog.google/products-and-platforms/devices/pixel/pixel-11-pro-fold/" },
      { label: "Google Blog: Pixel 11 launch features", url: "https://blog.google/products-and-platforms/devices/pixel/pixel-11-features/" },
      { label: "Google Blog: New Pixelsnap accessories for Pixel 11 phones", url: "https://blog.google/products-and-platforms/devices/pixel/new-pixelsnap-accessories-cases-ring-stand/" },
      { label: "Android Authority: Pixel 11 series launch coverage", url: "https://www.androidauthority.com/google-pixel-11-series-3693865/" },
      { label: "9to5Google: Made by Google 2026 launch coverage", url: "https://9to5google.com/2026/08/12/made-by-google-2026-announcements/" },
      { label: "The Verge: Made by Google 2026 event coverage", url: "https://www.theverge.com/tech/976454/made-by-google-2026-event-pixel-11-trevor-noah" }
    ],
    itemList: [
      "Pixel 11 starts at $899 with 12GB RAM and 256GB storage.",
      "Pixel 11 Pro starts at $1,099 and Pixel 11 Pro XL starts at $1,299.",
      "Pixel 11 Pro Fold starts at $1,899.",
      "Tensor G6 and Android 17 power all four phones.",
      "HiLight is available only on Pixel 11 Pro, Pro XL and Pro Fold.",
      "Pre-orders opened August 12 and retail availability begins August 20.",
      "Kenya is not listed among the initial launch markets."
    ],
    publicationStatus: "publish",
    editorialStatus: "published",
    indexingStatus: "index",
    hasOriginalPhotography: false
  };
}
